parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'

        types:
            json: Sonata\Doctrine\Types\JsonType
            attribute_array:  App\Doctrine\DBAL\Types\AttributeArray

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/vendor/bean-project//gdhh-core/Entity'
                        prefix: 'App\Entity'
                        alias: App

                entity_listeners:
                    entities:
                        -
                            class:  "App\\Entity\\HoSo\\ThanhVien"
                            listener:
                                -
                                    class: "App\\Doctrine\\ORM\\Listener\\HoSo\\ThanhVienListener"
                                    event:
                                        -
                                            type: postPersist
                                            method: postPersistHandler
                                        -
                                            type: postUpdate
                                            method: postUpdateHandler
                                        -
                                            type: prePersist
                                            method: prePersistHandler
                                        -
                                            type: preUpdate
                                            method: preUpdateHandler
                                        -
                                            type: preRemove
                                            method: preRemoveHandler
                                        -
                                            type: postRemove
                                            method: postRemoveHandler

                        -
                            class:  "App\\Entity\\HoSo\\PhanBo"
                            listener:
                                -
                                    class: "App\\Doctrine\\ORM\\Listener\\HoSo\\PhanBoListener"
                                    event:
                                        -
                                            type: postPersist
                                            method: postPersistHandler
                                        -
                                            type: postUpdate
                                            method: postUpdateHandler
                                        -
                                            type: prePersist
                                            method: prePersistHandler
                                        -
                                            type: preUpdate
                                            method: preUpdateHandler
                                        -
                                            type: preRemove
                                            method: preRemoveHandler
                                        -
                                            type: postRemove
                                            method: postRemoveHandler