fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     App\Entity\User\User
    from_email:
        address:              no-reply@magentapulse.com
        sender_name:          KPortal Auto Sender
    registration:
#        form:
#            type: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        confirmation:
            enabled:              false
            template:             'FOSUserBundle:Registration:email.txt.twig'
            from_email:
                address:              no-reply@magentapulse.com
                sender_name:          Interview-spot Auto Email
    resetting:
        token_ttl:            86400
        email:
            template:             'FOSUserBundle:Resetting:email.txt.twig'
            from_email:
                address:              no-reply@magentapulse.com
                sender_name:          Interview-spot Auto Email
    group:
        group_class:   App\Entity\User\Group
      #  group_manager: sonata.user.orm.group_manager
        # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

    #service:
     #   user_manager: sonata.user.orm.user_manager
        # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
