services:
    app.admin.security.menu_listener_huynhtruong:
        class: App\Admin\MenuBuilderListener
        arguments: ['@App\Service\User\UserService','@service_container']
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

sonata_admin:
    title: 'Gia Đình Hòa Hưng'
    options:
        title_mode: 'single_text'

    dashboard:
#        blocks:
#            - { type: sonata.admin.block.admin_list, position: left }
        groups: ~
    security:
        handler: sonata.admin.security.handler.role

    templates:
        layout: admin/standard_layout.html.twig
#        show: ::admin/show.html.twig
#        list_block: ::admin/block_admin_list.html.twig
#        inner_list_row: ::admin/list_inner_row.html.twig
#        edit: ::admin/edit.html.twig


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
