parameters:
    max_file_size: 150 # 150 MB per file
    max_file_per_user: 7 # 7 files
    video_thumbnail_pos: 3 # at the 3rd second
    video_thumbnail_resolution: 300x225 # width 300, height: 225 px

    s3_version: latest
    s3_bucket_name: magenta-consulting.com
    s3_region: ap-southeast-1


sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Entity\Media\Media
        gallery: App\Entity\Media\Gallery
        gallery_has_media: App\Entity\Media\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # could be doctrine_orm, doctrine_mongodb or doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            download:
#                strategy: app.sonata_media.security.user_strategy
                mode: http

            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        ipa_audio:
            download:
#                strategy: app.sonata_media.security.user_strategy
                mode: http

            providers:
                - sonata.media.provider.file

        audio_file:
            download:
#                strategy: app.sonata_media.security.user_strategy
                mode: http
            providers:
                - sonata.media.provider.file

        thumbnail:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
#                big:   { width: 500 , quality: 70}

#        sonata_collection:
#            providers:
#                - sonata.media.provider.image
#            formats:
#                preview: { width: 100, quality: 100}
#                wide:    { width: 820, quality: 100}


#    cdn:
#        server:
#            path: /uploads/media # http://media.sonata-project.org/
    cdn:
        # The CDN part must point to the base root of your application with a valid htaccess to match non existant
        # file. The non existant image will be send to the SonataMediaBundle:Media:liipImagineFilter controller.
        server:
#            path:     %app_baseroute% #http://mydomain.com
            path: http://%s3_bucket_name%.s3-website-%s3_region%.amazonaws.com
#            path: http://%s3_region%/%s3_bucket_name% # this one is no longer working
#            path: /uploads/media # http://media.sonata-project.org/
#http://s3-ap-southeast-1.amazonaws.com/magenta-consulting.com/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
        s3:
            bucket:      "%s3_bucket_name%"
            accessKey:   '%env(resolve:S3_ACCESS_KEY)%'
            secretKey:   '%env(resolve:S3_SECRET_KEY)%'
            region:      "%s3_region%"
            version:     "%s3_version%" # latest by default (cf. https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#version)
            sdk_version: 3 # 2 by default - "%s3_sdk_version%" is no longer permissable
            directory:   '%env(resolve:S3_DIRECTORY)%'

            create:         false
            #region:         s3.amazonaws.com # change if not using US Standard region
            storage:        standard # can be one of: standard or reduced
            acl:            public # can be one of: public, private, open, auth_read, owner_read, owner_full_control
#            encryption:     aes256 # can be aes256 or not set
            cache_control:  max-age=86400 # or any other
#            meta:
 #               key1:       value1 #any amount of metas(sent as x-amz-meta-key1 = value1)


# providers:
#        image:
#            resizer: sonata.media.resizer.square
#            filesystem: sonata.media.filesystem.s3
#        file:
#            resizer: false
#            filesystem: sonata.media.filesystem.s3
#            service:    sonata.media.provider.file
#            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml','png','jpg','jpeg','webm','wav','blob','','mp4']
#            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain','application/json','image/png','image/jpg','image/jpeg','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/x-wav','video/webm','application/octet-stream','video/mp4','binary/octet-stream']

    providers:
        # ...
        file:
            filesystem: sonata.media.filesystem.s3
#            thumbnail:  app.sonata_media.thumbnail.file

#            generator: app.sonata.media.generator.default
            allowed_extensions:
                - mp3
#                - mp4
                # Defaults:
                - pdf
                - txt
                - rtf
                - doc
                - docx
                - xls
                - xlsx
                - ppt
                - pptx
                - odt
                - odg
                - odp
                - ods
                - odc
                - odf
                - odb
                - csv
                - xml
            allowed_mime_types:
                - audio/mpeg
                - application/octet-stream
#                - video/mp4
                - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                # Defaults:
                - application/pdf
                - application/x-pdf
                - application/rtf
                - text/html
                - text/rtf
                - text/plain
                - application/excel
                - application/msword
                - application/vnd.ms-excel
                - application/vnd.ms-powerpoint
                - application/vnd.ms-powerpoint
                - application/vnd.oasis.opendocument.text
                - application/vnd.oasis.opendocument.graphics
                - application/vnd.oasis.opendocument.presentation
                - application/vnd.oasis.opendocument.spreadsheet
                - application/vnd.oasis.opendocument.chart
                - application/vnd.oasis.opendocument.formula
                - application/vnd.oasis.opendocument.database
                - application/vnd.oasis.opendocument.image
                - text/comma-separated-values
                - text/xml
                - application/xml
                - application/zip

        image:
            resizer: sonata.media.resizer.square
#            thumbnail:  sonata.media.thumbnail.liip_imagine
            filesystem: sonata.media.filesystem.s3
#            generator: app.sonata.media.generator.default
#        vimeo:
#            thumbnail:  sonata.media.thumbnail.liip_imagine
        youtube:
            filesystem: sonata.media.filesystem.s3

#            thumbnail:  sonata.media.thumbnail.liip_imagine
#        dailymotion:
#            thumbnail:  sonata.media.thumbnail.liip_imagine
