services:
    app.admin.security.menu_listener_huynhtruong:
        class: App\Admin\MenuBuilderListener
        arguments: ['@App\Service\User\UserService','@service_container']
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

#    App\Admin\User\UserAdmin: '@app.admin.user'
#    app.admin.user:
#        class: App\Admin\User\UserAdmin
#        arguments: [~, App\Entity\User\User, App\Admin\User\UserAdminController]
#        calls:
#            - [setTranslationDomain, ['SonataAdminBundle']]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: user, label_translator_strategy: sonata.admin.label.strategy.underscore }
#
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
#            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]

sonata_admin:
    title: 'Gia Đình Hòa Hưng'
    options:
        title_mode: 'single_text'

    dashboard:
        blocks: ~
#            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            system:
                label: dashboard.system
                icon: '<i class="fa fa-users"></i>'
                items:
                    - App\Admin\User\UserAdmin
                    - App\Admin\HoSo\NamHocAdmin
#                    - Sonata\MediaBundle\Admin\MediaAdmin
                    - sonata.media.admin.media
#                    - sonata.user.admin.group
#                    - sonata.classification.admin.context
#                    - sonata.classification.admin.category
#                    - sonata.classification.admin.collection
#                    - sonata.classification.admin.tag
#                    - sonata.notification.admin.message
    security:
        handler: sonata.admin.security.handler.role

    templates:
        layout: admin/standard_layout.html.twig
        user_block: admin/core/user_block.html.twig
#        show: ::admin/show.html.twig
#        list_block: ::admin/block_admin_list.html.twig
#        inner_list_row: ::admin/list_inner_row.html.twig
#        edit: ::admin/edit.html.twig


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
