<?php

namespace App\Command;

use App\Entity\HuynhTruong;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class GenerateTruongCommand extends Command
{
    const FIELD_CHRISTIAN_NAME = 'CNAME';
    const FIELD_NAME = 'NAME';
    const FIELD_AKA = 'AKA';
    const FIELD_DOB = 'DOB';
    const FIELD_PD = 'PD';
    const FIELD_CD = 'CD';
    const FIELD_FIRST = 'FNAME';

    const NGHIA = 'NGHIA';
    const TONGDO = 'TONGDO';

    const dsTruong = [

        [
            'id' => 649,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRANG',
            self::FIELD_NAME => 'MARIA ĐỖ THỊ ÁNH TRANG',
            self::FIELD_AKA => 'ÁNH TRANG',
            self::FIELD_DOB => 2017,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 650,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'ĐẠI',
            self::FIELD_NAME => 'GIUSE NGUYỄN QUANG ĐẠI',
            self::FIELD_AKA => 'QUANG ĐẠI',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 0,
        ],
        [
            'id' => 652,
            self::FIELD_CHRISTIAN_NAME => 'VINH-SƠN (VINCENTE)',
            self::FIELD_FIRST => 'DUY',
            self::FIELD_NAME => 'VINH-SƠN (VINCENTE) NGUYỄN VŨ ANH DUY',
            self::FIELD_AKA => 'ANH DUY Ái',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 716,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'PHƯỚC',
            self::FIELD_NAME => 'PHERO NGUYỄN HỒNG PHƯỚC',
            self::FIELD_AKA => 'HỒNG PHƯỚC',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 950,
            self::FIELD_CHRISTIAN_NAME => 'MÁC-CÔ (MARK)',
            self::FIELD_FIRST => 'LỘC',
            self::FIELD_NAME => 'MÁC-CÔ (MARK) NGUYỄN PHƯỚC LỘC',
            self::FIELD_AKA => 'PHƯỚC LỘC',
            self::FIELD_DOB => 1991,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 951,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'Toàn',
            self::FIELD_NAME => 'PHERO Nguyễn Đức Song Toàn',
            self::FIELD_AKA => 'Song Toàn',
            self::FIELD_DOB => 1988,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 952,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'BÌNH',
            self::FIELD_NAME => 'PHERO LÊ THANH BÌNH',
            self::FIELD_AKA => 'THANH BÌNH',
            self::FIELD_DOB => 1987,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 16,
        ],
        [
            'id' => 1023,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'THỊNH',
            self::FIELD_NAME => 'GIUSE TRẦN CÔNG THỊNH',
            self::FIELD_AKA => 'CÔNG THỊNH',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1027,
            self::FIELD_CHRISTIAN_NAME => 'ANNA',
            self::FIELD_FIRST => 'VI',
            self::FIELD_NAME => 'ANNA MAI TƯỜNG VI',
            self::FIELD_AKA => 'TƯỜNG VI',
            self::FIELD_DOB => 1998,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1028,
            self::FIELD_CHRISTIAN_NAME => 'MICAE',
            self::FIELD_FIRST => 'TRÍ',
            self::FIELD_NAME => 'MICAE VŨ QUANG TRÍ',
            self::FIELD_AKA => 'QUANG TRÍ',
            self::FIELD_DOB => 1987,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 15,
        ],
        [
            'id' => 1029,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'Huy',
            self::FIELD_NAME => 'PHERO Đặng Quang Huy',
            self::FIELD_AKA => 'Quang Huy',
            self::FIELD_DOB => 1985,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 15,
        ],
        [
            'id' => 1030,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'HẬU',
            self::FIELD_NAME => 'TERESA PHẠM THANH HẬU',
            self::FIELD_AKA => 'THANH HẬU',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1031,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'LOAN',
            self::FIELD_NAME => 'MARIA NGUYỄN NGỌC HỒNG LOAN',
            self::FIELD_AKA => 'chị LOAN lớn',
            self::FIELD_DOB => 1986,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 1032,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'HÀ',
            self::FIELD_NAME => 'MARIA TRẦN THỊ NGỌC HÀ',
            self::FIELD_AKA => 'NGỌC HÀ',
            self::FIELD_DOB => 1976,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1034,
            self::FIELD_CHRISTIAN_NAME => 'MICAE',
            self::FIELD_FIRST => 'HẬU',
            self::FIELD_NAME => 'MICAE VÕ PHÚC HẬU',
            self::FIELD_AKA => 'PHÚC HẬU',
            self::FIELD_DOB => 1979,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1035,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'TUYỀN',
            self::FIELD_NAME => 'TERESA NGUYỄN THỊ THANH TUYỀN',
            self::FIELD_AKA => 'THANH TUYỀN',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1036,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'MAI',
            self::FIELD_NAME => 'MARIA NGÔ THỊ NGỌC MAI',
            self::FIELD_AKA => 'NGỌC MAI',
            self::FIELD_DOB => 1951,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1039,
            self::FIELD_CHRISTIAN_NAME => 'VINH-SƠN (VINCENTE)',
            self::FIELD_FIRST => 'TÙNG',
            self::FIELD_NAME => 'VINH-SƠN (VINCENTE) ĐỖ XUÂN TÙNG',
            self::FIELD_AKA => 'XUÂN TÙNG',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 17,
        ],
        [
            'id' => 1040,
            self::FIELD_CHRISTIAN_NAME => 'PHANXICO-ASSISI',
            self::FIELD_FIRST => 'LONG',
            self::FIELD_NAME => 'PHANXICO-ASSISI TRẦN ĐỨC LONG',
            self::FIELD_AKA => 'ĐỨC LONG',
            self::FIELD_DOB => 1984,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 0,
        ],
        [
            'id' => 1041,
            self::FIELD_CHRISTIAN_NAME => 'PHANXICO-ASSISI',
            self::FIELD_FIRST => 'DANH',
            self::FIELD_NAME => 'PHANXICO-ASSISI NGUYỄN VĂN DANH',
            self::FIELD_AKA => 'VĂN DANH',
            self::FIELD_DOB => 1984,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1042,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'KHOA',
            self::FIELD_NAME => 'PHERO LÊ ĐĂNG KHOA',
            self::FIELD_AKA => 'ĐĂNG KHOA',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1043,
            self::FIELD_CHRISTIAN_NAME => 'TOMA',
            self::FIELD_FIRST => 'ANH',
            self::FIELD_NAME => 'TOMA NGUYỄN PHẠM TUẤN ANH',
            self::FIELD_AKA => 'TUẤN ANH',
            self::FIELD_DOB => 1994,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1044,
            self::FIELD_CHRISTIAN_NAME => 'MARIA-GORETTI',
            self::FIELD_FIRST => 'VY',
            self::FIELD_NAME => 'MARIA-GORETTI NGUYỄN THUÝ VY',
            self::FIELD_AKA => 'THUÝ VY',
            self::FIELD_DOB => 1977,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1045,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRÂM',
            self::FIELD_NAME => 'MARIA VÕ LÊ NGỌC TRÂM',
            self::FIELD_AKA => 'NGỌC TRÂM',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
        [
            'id' => 1046,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'TUẤN',
            self::FIELD_NAME => 'GIUSE PHẠM ANH TUẤN',
            self::FIELD_AKA => 'ANH TUẤN',
            self::FIELD_DOB => 1992,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1047,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'THUỲ',
            self::FIELD_NAME => 'MARIA NGUYỄN NGỌC THUỲ',
            self::FIELD_AKA => 'NGỌC THUỲ',
            self::FIELD_DOB => 1977,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 14,
        ],
        [
            'id' => 1048,
            self::FIELD_CHRISTIAN_NAME => 'MARIA-TERESA',
            self::FIELD_FIRST => 'DIỄM',
            self::FIELD_NAME => 'MARIA-TERESA PHẠM NGỌC THUÝ DIỄM',
            self::FIELD_AKA => 'THUÝ DIỄM',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1052,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'DIỄM',
            self::FIELD_NAME => 'MARIA ĐẶNG NGỌC DIỄM',
            self::FIELD_AKA => 'NGỌC DIỄM',
            self::FIELD_DOB => 1972,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1053,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'DUY',
            self::FIELD_NAME => 'GIUSE TRẦN ĐỨC DUY',
            self::FIELD_AKA => 'anh DUY mủm mỉm',
            self::FIELD_DOB => 1997,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1054,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'THY',
            self::FIELD_NAME => 'MARIA NGUYỄN PHƯƠNG QUỲNH THY',
            self::FIELD_AKA => 'QUỲNH THY',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 18,
        ],
        [
            'id' => 1055,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'ANH',
            self::FIELD_NAME => 'MARIA NGUYỄN NGỌC ANH',
            self::FIELD_AKA => 'NGỌC ANH',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1056,
            self::FIELD_CHRISTIAN_NAME => 'GIOAN-BAOTIXITA',
            self::FIELD_FIRST => 'TRUNG',
            self::FIELD_NAME => 'GIOAN-BAOTIXITA ĐẶNG QUANG TRUNG',
            self::FIELD_AKA => 'QUANG TRUNG',
            self::FIELD_DOB => 1985,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1057,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'QUANG',
            self::FIELD_NAME => 'GIUSE TRẦN ĐỨC QUANG',
            self::FIELD_AKA => 'ĐỨC QUANG',
            self::FIELD_DOB => 1997,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1058,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'ANH',
            self::FIELD_NAME => 'MARIA TRIỆU TƯỜNG VÂN ANH',
            self::FIELD_AKA => 'VÂN ANH',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 1059,
            self::FIELD_CHRISTIAN_NAME => 'ANTON',
            self::FIELD_FIRST => 'KHÁNH',
            self::FIELD_NAME => 'ANTON HOÀNG MINH KHÁNH',
            self::FIELD_AKA => 'MINH KHÁNH',
            self::FIELD_DOB => 1993,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 1060,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'DUY',
            self::FIELD_NAME => 'GIUSE ĐẶNG ĐỨC DUY',
            self::FIELD_AKA => 'anh DUY gầy',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1061,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'LOAN',
            self::FIELD_NAME => 'MARIA NGUYỄN THỊ HỒNG LOAN',
            self::FIELD_AKA => 'chị LOAN nhỏ; LOAN ba tập',
            self::FIELD_DOB => 1991,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1063,
            self::FIELD_CHRISTIAN_NAME => 'ANNA',
            self::FIELD_FIRST => 'NGHI',
            self::FIELD_NAME => 'ANNA HOÀNG NGỌC BẢO NGHI',
            self::FIELD_AKA => 'BẢO NGHI',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 1064,
            self::FIELD_CHRISTIAN_NAME => 'CATARINA',
            self::FIELD_FIRST => 'DƯƠNG',
            self::FIELD_NAME => 'CATARINA NGUYỄN THỊ THUỲ DƯƠNG',
            self::FIELD_AKA => 'THUỲ DƯƠNG',
            self::FIELD_DOB => 1991,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 1065,
            self::FIELD_CHRISTIAN_NAME => 'ANTON',
            self::FIELD_FIRST => 'NGUYÊN',
            self::FIELD_NAME => 'ANTON LÊ CÔNG NGUYÊN',
            self::FIELD_AKA => 'CÔNG NGUYÊN',
            self::FIELD_DOB => 1997,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1066,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'HƯNG',
            self::FIELD_NAME => 'PHERO DƯƠNG TIẾN HƯNG',
            self::FIELD_AKA => 'TIẾN HƯNG',
            self::FIELD_DOB => 1997,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1068,
            self::FIELD_CHRISTIAN_NAME => 'ANNA',
            self::FIELD_FIRST => 'AN',
            self::FIELD_NAME => 'ANNA ĐẶNG THUỲ AN',
            self::FIELD_AKA => 'THUỲ AN',
            self::FIELD_DOB => 1993,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 15,
        ],
        [
            'id' => 1069,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'YẾN',
            self::FIELD_NAME => 'MARIA LÊ NGỌC YẾN',
            self::FIELD_AKA => 'NGỌC YẾN',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
        [
            'id' => 1071,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'NGA',
            self::FIELD_NAME => 'TERESA TRẦN MỸ NGA',
            self::FIELD_AKA => 'MỸ NGA',
            self::FIELD_DOB => 1989,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1072,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'LINH',
            self::FIELD_NAME => 'MARIA NGÔ THỊ THUỲ LINH',
            self::FIELD_AKA => 'THUỲ LINH',
            self::FIELD_DOB => 1972,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 1073,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'HUÂN',
            self::FIELD_NAME => 'GIUSE NGUYỄN ĐỨC HUÂN',
            self::FIELD_AKA => 'ĐỨC HUÂN',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1074,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'NHI',
            self::FIELD_NAME => 'TERESA LƯU NGỌC NHI',
            self::FIELD_AKA => 'NGỌC NHI',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1075,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'ANH',
            self::FIELD_NAME => 'TERESA TRẦN MỸ ANH',
            self::FIELD_AKA => 'MỸ ANH',
            self::FIELD_DOB => 1998,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 4,
        ],
        [
            'id' => 1076,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRINH',
            self::FIELD_NAME => 'MARIA VŨ NGỌC TUYẾT TRINH',
            self::FIELD_AKA => 'TUYẾT TRINH',
            self::FIELD_DOB => 1995,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1077,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'HIẾU',
            self::FIELD_NAME => 'GIUSE TỪ TRUNG HIẾU',
            self::FIELD_AKA => 'TRUNG HIẾU',
            self::FIELD_DOB => 1984,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1078,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'PHƯƠNG',
            self::FIELD_NAME => 'MARIA NGUYỄN HOÀNG ÁI PHƯƠNG',
            self::FIELD_AKA => 'ÁI PHƯƠNG',
            self::FIELD_DOB => 1980,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 4,
        ],
        [
            'id' => 1079,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'QUỐC',
            self::FIELD_NAME => 'PHERO NGUYỄN ANH QUỐC',
            self::FIELD_AKA => 'ANH QUỐC',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 1083,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'QUYÊN',
            self::FIELD_NAME => 'TERESA TRẦN THỊ TỐ QUYÊN',
            self::FIELD_AKA => 'TỐ QUYÊN',
            self::FIELD_DOB => 1976,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1085,
            self::FIELD_CHRISTIAN_NAME => 'ELIZABETH',
            self::FIELD_FIRST => 'VY',
            self::FIELD_NAME => 'ELIZABETH PHẠM THÚY VY',
            self::FIELD_AKA => 'THÚY VY',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1086,
            self::FIELD_CHRISTIAN_NAME => 'ELIZABETH',
            self::FIELD_FIRST => 'HÒA',
            self::FIELD_NAME => 'ELIZABETH NGUYỄN THỊ HÒA',
            self::FIELD_AKA => 'THỊ HÒA',
            self::FIELD_DOB => 1997,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1095,
            self::FIELD_CHRISTIAN_NAME => 'ANTON',
            self::FIELD_FIRST => 'VINH',
            self::FIELD_NAME => 'ANTON TRẦN ĐỨC VINH',
            self::FIELD_AKA => 'ĐỨC VINH',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1097,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRÂM',
            self::FIELD_NAME => 'MARIA NGUYỄN THỊ HUYỀN TRÂM',
            self::FIELD_AKA => 'HUYỀN TRÂM',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1105,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'NGÂN',
            self::FIELD_NAME => 'TERESA VÕ THỊ KIM NGÂN',
            self::FIELD_AKA => 'KIM NGÂN',
            self::FIELD_DOB => 1987,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1106,
            self::FIELD_CHRISTIAN_NAME => 'TOMA',
            self::FIELD_FIRST => 'TUẤN',
            self::FIELD_NAME => 'TOMA PHẠM THANH TUẤN',
            self::FIELD_AKA => 'THANH TUẤN',
            self::FIELD_DOB => 1975,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1107,
            self::FIELD_CHRISTIAN_NAME => 'ANNA',
            self::FIELD_FIRST => 'LAN',
            self::FIELD_NAME => 'ANNA NGUYỄN VŨ QUỲNH LAN',
            self::FIELD_AKA => 'QUỲNH LAN',
            self::FIELD_DOB => 1994,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 17,
        ],
        [
            'id' => 1108,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TIÊN',
            self::FIELD_NAME => 'MARIA NGUYỄN THỊ THỦY TIÊN',
            self::FIELD_AKA => 'THỦY TIÊN',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 7,
        ],
        [
            'id' => 1109,
            self::FIELD_CHRISTIAN_NAME => 'CATARINA',
            self::FIELD_FIRST => 'TỈ',
            self::FIELD_NAME => 'CATARINA VÕ HOÀI HƯƠNG TỈ',
            self::FIELD_AKA => 'HƯƠNG TỈ',
            self::FIELD_DOB => 1987,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1110,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'THUẬN',
            self::FIELD_NAME => 'GIUSE TRẦN THẾ THUẬN',
            self::FIELD_AKA => 'THẾ THUẬN',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1112,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'HUYỀN',
            self::FIELD_NAME => 'TERESA TRẦN THỊ THU HUYỀN',
            self::FIELD_AKA => 'THU HUYỀN',
            self::FIELD_DOB => 1992,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 10,
        ],
        [
            'id' => 1113,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRÚC',
            self::FIELD_NAME => 'MARIA ĐỖ PHẠM THANH TRÚC',
            self::FIELD_AKA => 'THANH TRÚC',
            self::FIELD_DOB => 1993,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 12,
        ],
        [
            'id' => 1114,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'CÔNG',
            self::FIELD_NAME => 'GIUSE HOÀNG PHAN CÔNG',
            self::FIELD_AKA => 'PHAN CÔNG',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 16,
        ],
        [
            'id' => 1115,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'HẰNG',
            self::FIELD_NAME => 'TERESA VŨ THỊ THÚY HẰNG',
            self::FIELD_AKA => 'THÚY HẰNG',
            self::FIELD_DOB => 1985,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 1116,
            self::FIELD_CHRISTIAN_NAME => 'MATTA (MÁC-TA)',
            self::FIELD_FIRST => 'NHI',
            self::FIELD_NAME => 'MATTA (MÁC-TA) NGUYỄN THỤY NGỌC NHI',
            self::FIELD_AKA => 'NGỌC NHI',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 13,
        ],
        [
            'id' => 1117,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TIÊN',
            self::FIELD_NAME => 'MARIA NGUYỄN TRẦN PHÚ HUỲNH TIÊN',
            self::FIELD_AKA => 'HUỲNH TIÊN',
            self::FIELD_DOB => 1994,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 14,
        ],
        [
            'id' => 1118,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'PHÚ',
            self::FIELD_NAME => 'GIUSE PHẠM NGUYỄN THIÊN PHÚ',
            self::FIELD_AKA => 'THIÊN PHÚ',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1119,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'DIỄM',
            self::FIELD_NAME => 'MARIA TRẦN THỊ HOÀI DIỄM',
            self::FIELD_AKA => 'HOÀI DIỄM',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 14,
        ],
        [
            'id' => 1122,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'NHẬT',
            self::FIELD_NAME => 'GIUSE PHẠM THANH NHẬT',
            self::FIELD_AKA => 'THANH NHẬT',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1123,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'OANH',
            self::FIELD_NAME => 'TERESA HOÀNG OANH',
            self::FIELD_AKA => 'HOÀNG OANH',
            self::FIELD_DOB => 1987,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 9,
        ],
        [
            'id' => 1127,
            self::FIELD_CHRISTIAN_NAME => 'PHAOLO',
            self::FIELD_FIRST => 'LỘC',
            self::FIELD_NAME => 'PHAOLO NGUYỄN PHI LỘC',
            self::FIELD_AKA => 'PHI LỘC',
            self::FIELD_DOB => 1991,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 6,
        ],
        [
            'id' => 1129,
            self::FIELD_CHRISTIAN_NAME => 'PHERO',
            self::FIELD_FIRST => 'HƯNG',
            self::FIELD_NAME => 'PHERO TRẦN PHẠM PHÚC HƯNG',
            self::FIELD_AKA => 'PHÚC HƯNG',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
        [
            'id' => 1130,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'HẠ',
            self::FIELD_NAME => 'MARIA ĐỖ THÙY TRANG HẠ',
            self::FIELD_AKA => 'TRANG HẠ',
            self::FIELD_DOB => 1992,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 4,
        ],
        [
            'id' => 1181,
            self::FIELD_CHRISTIAN_NAME => 'DOMINICO',
            self::FIELD_FIRST => 'QUÝ',
            self::FIELD_NAME => 'DOMINICO NGUYỄN HOÀNG QUÝ',
            self::FIELD_AKA => 'HOÀNG QUÝ',
            self::FIELD_DOB => 1992,
            self::FIELD_PD => 'Thiếu Nhi',
            self::FIELD_CD => 11,
        ],
        [
            'id' => 1183,
            self::FIELD_CHRISTIAN_NAME => 'PHANXICO',
            self::FIELD_FIRST => 'Nghĩa',
            self::FIELD_NAME => 'PHANXICO Chu Gia Nghĩa',
            self::FIELD_AKA => 'Gia Nghĩa',
            self::FIELD_DOB => 1982,
            self::FIELD_PD => 'Tông Đồ/ Hiệp sỹ',
            self::FIELD_CD => 0,
        ],
        [
            'id' => 1184,
            self::FIELD_CHRISTIAN_NAME => 'GIUSE',
            self::FIELD_FIRST => 'ĐỨC',
            self::FIELD_NAME => 'GIUSE NGÔ HỮU ĐỨC',
            self::FIELD_AKA => 'HỮU ĐỨC',
            self::FIELD_DOB => 1996,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
        [
            'id' => 1241,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'TRANG',
            self::FIELD_NAME => 'MARIA NGUYỄN HOÀNG THUỲ TRANG',
            self::FIELD_AKA => '',
            self::FIELD_DOB => 2000,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
        [
            'id' => 1247,
            self::FIELD_CHRISTIAN_NAME => 'TERESA',
            self::FIELD_FIRST => 'PHƯƠNG',
            self::FIELD_NAME => 'TERESA ĐẶNG THÁI BẢO PHƯƠNG',
            self::FIELD_AKA => 'Bảo Phương',
            self::FIELD_DOB => 2000,
            self::FIELD_PD => 'Ấu Nhi',
            self::FIELD_CD => 8,
        ],
        [
            'id' => 1323,
            self::FIELD_CHRISTIAN_NAME => 'PHAOLO',
            self::FIELD_FIRST => 'Chương',
            self::FIELD_NAME => 'PHAOLO Nguyễn Văn Chương',
            self::FIELD_AKA => 'Văn Chương',
            self::FIELD_DOB => 1993,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 15,
        ],
        [
            'id' => 1324,
            self::FIELD_CHRISTIAN_NAME => 'PHAOLO',
            self::FIELD_FIRST => 'CÔNG',
            self::FIELD_NAME => 'PHAOLO NGUYỄN KIM CÔNG',
            self::FIELD_AKA => 'kimcong',
            self::FIELD_DOB => 0,
            self::FIELD_PD => 'Nghĩa Sĩ',
            self::FIELD_CD => 14,
        ],
        [
            'id' => 1325,
            self::FIELD_CHRISTIAN_NAME => 'MARIA',
            self::FIELD_FIRST => 'NGÂN',
            self::FIELD_NAME => 'MARIA NGUYỄN THỊ THỦY NGÂN',
            self::FIELD_AKA => 'Thủy Ngân',
            self::FIELD_DOB => 1998,
            self::FIELD_PD => 'Chiên Con',
            self::FIELD_CD => 5,
        ],
    ];

    protected static $defaultName = 'app:generate:truong';

    private $em;

    public function __construct(string $name = null, EntityManagerInterface $em)
    {
        parent::__construct($name);
        $this->em = $em;
    }

    protected function configure()
    {
        $this
            ->setDescription('Add a short description for your command')
            ->addArgument('arg1', InputArgument::OPTIONAL, 'Argument description')
            ->addOption('option1', null, InputOption::VALUE_NONE, 'Option description');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $arg1 = $input->getArgument('arg1');

        if ($arg1) {
            $io->note(sprintf('You passed an argument: %s', $arg1));
        }

        if ($input->getOption('option1')) {
            // ...
        }

        $truongs = $this->em->getRepository(HuynhTruong::class)->findAll();
        foreach ($truongs as $truong) {
            $this->em->remove($truong);
        }
        $this->em->flush();

        foreach (self::dsTruong as $data) {
            $tr = new HuynhTruong();
            $tr->setName($data[self::FIELD_NAME]);
            $tr
                ->setFirstName($data[self::FIELD_FIRST])
                ->setEnabled(true)
                ->setAka($data[self::FIELD_AKA])
                ->setChristianName($data[self::FIELD_CHRISTIAN_NAME])
                ->setChiDoan($data[self::FIELD_CD])
                ->setPhanDoan($data[self::FIELD_PD]);
            $this->em->persist($tr);
        }
        $this->em->flush();

        $io->success('You have a new command! Now make it your own! Pass --help to see your options.');

        return 0;
    }
}
